package com.seshi.loanapplication;

import static org.junit.jupiter.api.Assertions.assertAll;
import static org.junit.jupiter.api.Assertions.assertEquals;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.Test;

class DatabaseMigrationTests {

    @Test
    void migratesLegacyCompanyRowsWithoutDataLoss() throws Exception {
        String databaseUrl = "jdbc:h2:mem:legacy_loan_test;MODE=MySQL;DB_CLOSE_DELAY=-1";

        try (Connection connection = DriverManager.getConnection(databaseUrl, "sa", "");
                Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE companies (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        company_name VARCHAR(150) NOT NULL,
                        credit_score INT NOT NULL,
                        total_assets DECIMAL(19, 2) NOT NULL,
                        requested_loan_amount DECIMAL(19, 2) NOT NULL
                    )
                    """);
            statement.executeUpdate("""
                    INSERT INTO companies
                        (company_name, credit_score, total_assets, requested_loan_amount)
                    VALUES
                        ('Legacy Bakery LLC', 710, 250000.00, 75000.00)
                    """);
        }

        Flyway.configure()
                .dataSource(databaseUrl, "sa", "")
                .locations("classpath:db/migration/h2")
                .baselineOnMigrate(true)
                .baselineVersion("1")
                .load()
                .migrate();

        try (Connection connection = DriverManager.getConnection(databaseUrl, "sa", "");
                Statement statement = connection.createStatement();
                ResultSet result = statement.executeQuery("SELECT * FROM companies WHERE id = 1")) {
            result.next();

            assertAll(
                    () -> assertEquals("Legacy Bakery LLC", result.getString("company_name")),
                    () -> assertEquals(710, result.getInt("credit_score")),
                    () -> assertEquals(new BigDecimal("250000.00"), result.getBigDecimal("total_assets")),
                    () -> assertEquals(new BigDecimal("75000.00"), result.getBigDecimal("requested_loan_amount")),
                    () -> assertEquals("OTHER", result.getString("business_structure")),
                    () -> assertEquals("TERM_LOAN", result.getString("loan_type")),
                    () -> assertEquals("SUBMITTED", result.getString("application_status")),
                    () -> assertEquals("migration-required@example.invalid", result.getString("contact_email")),
                    () -> assertEquals(null, result.getString("country_of_registration")),
                    () -> assertEquals(null, result.getString("ssn_last_four")));
        }
    }
}
